<?php

/**
 * @file
 * An Islandora viewer module using Video.js
 */

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_audiojs_islandora_viewer_info() {
  return array(
    'islandora_audiojs' => array(
      'label' => t('audio.js player'),
      'description' => t('audio.js for audio.'),
      'callback' => 'islandora_audiojs_callback',
      'mimetype' => array('audio/mpeg', 'audio/mp3'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_audiojs_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_audiojs' => array(
      'template' => 'theme/islandora-audiojs',
      'variables' => array('object' => NULL, 'params' => NULL),
    ),
  );
}

/**
 * Implements hook_preprocess().
 */
function islandora_audiojs_preprocess_islandora_audiojs(array &$variables) {
  $params = $variables['params'];
  $variables['tn'] = isset($params['tn']) ? $params['tn'] : NULL;
  $audiojs_path = libraries_get_path("audiojs");
  drupal_add_js($audiojs_path . "/audiojs/audio.min.js");
  drupal_add_css($audiojs_path . 'includes/index.css');

  $variables['sources'][] = array('url' => $params['url'], 'mime' => $params['mime']);
}

/**
 * Callback function to process audio player.
 *
 * @param array $params
 *   Array with configuration info for the audio player.
 */
function islandora_audiojs_callback($params = array()) {
  return theme('islandora_audiojs', array('params' => $params));
}
